
export default {
  zh: {
    i18nView: {
      myAlert: '最新告警:',
      startTime: '开始时间:',
      assignedTo: '发送给:',
      upgradeTime: '更新时间:',
      ivrStatus: 'IVR 状态:',
      endTime: '结束时间:',
      bridgeStatus: 'Bridge 状态:',
      triggerCriteria: 'Trigger Criteria:',
      assginToMe: '发送给我',
      ivrMessage: 'IVR 信息',
      resolve: '解决',
      reactivate: 'Reactivate',
      actions: '动作',
      view: '视图',
      log: '日志',
      site1: '网站 1',
      site2: '网站 2',
      businessSegment: 'Business Segment:',
      origanization: 'Origanization:',
      queueDetails: 'QueueDetails:',
      region: '地区:',
      modality: 'Modality:',
      language: '语言:',
      metric1: 'Metric1:',
      metric2: 'Metric2:',
      metric3: 'Metric3:',
      metric4: 'Metric4:',
      metric5: 'Metric5:',
      metric6: 'Metric6:',
      metric7: 'Metric7:',
      metric8: 'Metric8:',
      newAlert: '新的告警',
      assgintoNewalert: '有人发送给你一个新的告警',
      seeMoreDetail: '查看详情',
      customlogEntry: '自定义用户日志',
      inquiryRequest: '发送请求',
      sitePhone: 'Site Phone:',
      distributionList: 'Distribution List:',
      primarySDM: 'Primary SDM:',
      secondarySDM: 'Secondary SDM:',
      tertiarySDM: 'Tertiary SDM: ',
      lastContactTime: 'Last Contact Time:',
      timeElapsed: 'Time Elapsed:',
      Monday: 'Monday',
      Tuesday: 'Tuesday',
      Wednesday: 'Wednesday',
      Thursday: 'Thursday',
      Friday: 'Friday',
      Saturday: 'Saturday',
      Sunday: 'Sunday',
      howrofoperation: 'Hour of Operation (PST):',
      status: 'Status'
    }
  },
  en: {
    i18nView: {
      myAlert: 'My Alerts',
      startTime: 'Start Time:',
      assignedTo: 'Assigned To:',
      upgradeTime: 'Upgrade Time:',
      ivrStatus: 'IVR Status:',
      endTime: 'End Time:',
      bridgeStatus: 'Bridge Status:',
      triggerCriteria: 'Trigger Criteria:',
      assginToMe: 'Assgin To Me',
      ivrMessage: 'IVR Message',
      resolve: 'Resolve',
      reactivate: 'Reactivate',
      actions: 'Actions',
      view: 'View',
      log: 'Log',
      site1: 'Site 1',
      site2: 'Site 2',
      businessSegment: 'Business Segment:',
      origanization: 'Origanization:',
      queueDetails: 'QueueDetails:',
      region: 'Region:',
      modality: 'Modality:',
      language: 'Language:',
      metric1: 'Metric1:',
      metric2: 'Metric2:',
      metric3: 'Metric3:',
      metric4: 'Metric4:',
      metric5: 'Metric5:',
      metric6: 'Metric6:',
      metric7: 'Metric7:',
      metric8: 'Metric8:',
      newAlert: 'Have a new alert',
      assgintoNewalert: 'Some one assgin to you a new alert',
      seeMoreDetail: 'See more details',
      customlogEntry: 'Custom Log Entry',
      inquiryRequest: 'Inquiry Request',
      sitePhone: 'Site Phone:',
      distributionList: 'Distribution List:',
      primarySDM: 'Primary SDM:',
      secondarySDM: 'Secondary SDM:',
      tertiarySDM: 'Tertiary SDM: ',
      lastContactTime: 'Last Contact Time:',
      timeElapsed: 'Time Elapsed:',
      Monday: 'Monday:',
      Tuesday: 'Tuesday:',
      Wednesday: 'Wednesday:',
      Thursday: 'Thursday:',
      Friday: 'Friday:',
      Saturday: 'Saturday:',
      Sunday: 'Sunday:',
      howrofoperation: 'Hour of Operation (PST)',
      status: 'Status'
    }
  }
}
